basePath: /
host: localhost:8000
info:
  contact:
    email: james.m.kobayashi@gmail.com
    name: James Kobayashi
  description: Product API with authentication
  title: Basic API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
